# Generated by Django 6.0.5 on 2026-05-19 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Напишите заголовок", max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, help_text="Напишите описание", verbose_name="Описание")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Напишите ссылку на оригинал",
                        null=True,
                        verbose_name="Ссылка на оригинал",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Напишите источник задачи",
                        max_length=255,
                        verbose_name="Откуда пришла задача(источник)",
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=200, verbose_name="ID в источнике")),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Напишите дату публикации",
                        verbose_name="Когда опубликована",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "новая"), ("in_progress", "в работе"), ("done", "выполнена")],
                        default="new",
                        help_text="Выберите статус",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-published_at"],
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
