# Generated by Django 6.0.5 on 2026-05-19 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MockTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Напишите заголовок", max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, help_text="Напишите описание", verbose_name="Описание")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Напишите ссылку на оригинал",
                        null=True,
                        verbose_name="Ссылка на оригинал",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Напишите дату публикации",
                        verbose_name="Когда опубликована",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Парсер перенёс задачу в основную таблицу",
                        verbose_name="Обработано/не обработано",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тестовая задача",
                "verbose_name_plural": "Тестовые задачи",
                "ordering": ["-published_at"],
            },
        ),
    ]
